version: "2"
services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/carrea2.tk/fullchain.pem:/etc/letsencrypt/live/carrea2.tk/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/carrea2.tk/privkey.pem:/etc/letsencrypt/live/carrea2.tk/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server      
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./mongodata:/data/db
    expose:
      - 27017
    #- "27017:27017"